export default {
    SET_USER_LOGIN_DATA: 'SET_USER_LOGIN_DATA',
    SET_USER_PROFILE_FIELDS: 'SET_USER_PROFILE_FIELDS',
    SET_USER_ID: 'SET_USER_ID',
    SET_USER_NAME: 'SET_USER_NAME',
    SET_MOBILE: 'SET_MOBILE',
    SET_USER_EMAIL: 'SET_USER_EMAIL',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_IS_LOGIN: 'SET_IS_LOGIN',
    SET_PROFILE_PICTURE: 'SET_PROFILE_PICTURE',
    SET_TOTAL_REFERRAL_AMT: 'SET_TOTAL_REFERRAL_AMT'
};

